### ISSUE TITLE
Changes aren't applied if the apply button is pressed and then the settings are saved afterwards.

### ISSUE THREAD

**Issue by danekshea** [OctoPrint/OctoPrint-Yamlpatcher#2] opened 2016-01-17 12:25 UTC
If you make a patch and press Apply then it will save but if you press Save Settings afterwards it will nullify the changes to config.yaml that you made.

**Comment by foosel** [comment] 2016-01-18 16:49
I was just about to ask which version of the plugin you were using because I couldn't reproduce it, then realized that I couldn't reproduce it doesn't happen here because it's actually an issue at how OctoPrint handles its settings and I fixed THAT in OctoPrint's `devel` branch. The changes are quite invasive though, so I haven't backported them to the stable branch. I'm still very unsure if I should do that. Thinking about that.

Without that change to OctoPrint's settings manager however, this is unfixable from YamlPatcher's side.

Leaving this open while trying to decide on a good solution.

**Comment by foosel** [comment] 2016-01-19 09:35
Feeling a bit dumb right now. Turns out I had actually been able to solve this issue without a change in OctoPrint, committed that change too - to the `devel` branch. And then forgot to create a release m)

I just released 0.1.1 which solves the problem.

**Closed by foosel** 2016-01-19 09:35 UTC
